// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1589703696);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1589703816);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1589382253);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1589703576);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1589703937);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "KR");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Thu, 14 May 2020 10:06:10 GMT");
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1589703698);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200110142707");
user_pref("extensions.lastAppVersion", "68.7.0");
user_pref("extensions.lastPlatformVersion", "68.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"6ea19b4b-da6e-4ad6-aeae-b70bc2f55dcb\",\"default-theme@mozilla.org\":\"c84905e5-c2d6-46e0-80b4-6f478a07bd88\",\"google@search.mozilla.org\":\"20d33566-c601-4008-937f-cc03aabc6a9d\",\"ddg@search.mozilla.org\":\"b0189de1-4237-48cf-8856-3ee7a8be5fd2\",\"naver-kr@search.mozilla.org\":\"34a1fcb8-29fe-4bf9-9621-d72f4a7de50c\",\"daum-kr@search.mozilla.org\":\"91bd7d40-6cac-434c-8d0f-a605e7ea53f4\",\"wikipedia@search.mozilla.org\":\"49382171-72c8-405d-8eb6-ec07a9e04867\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1589301968);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "e9c43c59-31ab-4233-b0f2-d197d585e00");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.7.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "중요");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "직장");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "개인");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "할일");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "연기");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1589301969);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "d584f1d0-4de8-45d4-8ca4-46a7f429d8d4");
user_pref("services.blocklist.pinning.checked", 1589703576);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1589697596111\"");
user_pref("services.settings.last_update_seconds", 1589703576);
user_pref("services.settings.main.hijack-blocklists.last_check", 1589703576);
user_pref("services.settings.main.language-dictionaries.last_check", 1589703576);
user_pref("services.settings.main.sites-classification.last_check", 1589703576);
user_pref("services.settings.security.onecrl.checked", 1589703576);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1589301968);
user_pref("toolkit.telemetry.cachedClientID", "5ef4a370-baf8-4759-9e98-ac1fc9049109");
user_pref("toolkit.telemetry.prompted", 2);
